In [24]:
import torch
from experiments.eventgen.transforms import EPPP_to_PtPhiEtaE, PtPhiEtaE_to_PtPhiEtaM2

In [25]:
jm = torch.tensor([ 5.6501e+01, -9.4960e-01,  1.6761e+00,  1.0000e-01])

In [47]:
jm = torch.tensor([ 5.6501e+01, -9.4960e-01,  1.6761e+00,  1.0000e-01])
print(jm)
tm = PtPhiEtaE_to_PtPhiEtaM2().inverse(jm)
print(tm)
fm = PtPhiEtaE_to_PtPhiEtaM2().forward(tm)
print(fm)
fm = EPPP_to_PtPhiEtaE().inverse(tm)
print(fm)
fm = EPPP_to_PtPhiEtaE().forward(fm)
print(fm)


tensor([56.5010, -0.9496,  1.6761,  0.1000])
tensor([ 56.5010,  -0.9496,   1.6761, 156.2757])
tensor([56.5010, -0.9496,  1.6761,  0.0996])
tensor([156.2757,  32.8841, -45.9456, 145.7039])
tensor([ 56.5010,  -0.9496,   1.6761, 156.2757])


In [51]:
print(fm)
tm = EPPP_to_PtPhiEtaE().inverse(fm)
print(tm)
jm = EPPP_to_PtPhiEtaE().forward(tm)
print(jm)

tensor([ 56.5010,  -0.9496,   1.6761, 156.2757])
tensor([156.2757,  32.8841, -45.9456, 145.7040])
tensor([ 56.5010,  -0.9496,   1.6761, 156.2757])


In [28]:
m2 = fm[..., 0] ** 2 - torch.sum(fm[..., 1:] ** 2, dim=-1)
m2 = torch.abs(m2)
m = torch.sqrt(m2.clamp(min=1e-6))
print(m)

tensor(0.3125)
